name: riverpod_http
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.3
  http: ^1.2.2
  convert: ^3.1.2
  freezed_annotation: ^2.4.4
  freezed: ^2.5.7
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:

  uses-material-design: true